### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by wraybowling** [wmd-glowforge/text2vector#4]
I don't see why this shouldn't be hosted with Github Pages. The browser will recognize the end user's system fonts. Most Glowforge users likely have no clue how to get started with git or won't want to be bothered with downloading HTML. The online version will always be up to date with master. Yeah. Just host it.

**Comment by wmd-glowforge** [comment]
It has been hosted for a while now:
https://wmd-glowforge.github.io/text2vector/

**Comment by wraybowling** [comment]
Thanks for updating the readme. Github repos can also have an associated URL; you can add the link there as well. Cheers!

**Comment by wmd-glowforge** [comment]
I added the repo link also!  I didn't think about that one, since that is how I access the file.  Thanks for the feedback!
